# Experiment Parameters
root_dir: lightning_logs

config_name: config.yaml
experiment_name: experiment
run_name: version000

predict_dir: samples

train_command: fit --trainer configs/trainer/config.test.yaml --model configs/model/config.yaml --data configs/data/local.yaml
correlation_command: --trainer configs/trainer/config.test.yaml --model configs/model/config.yaml

categories:
- 'donor_id'
- 'assay'
- 'dataset_id'
- 'cell_type'
- 'tissue'
- 'species'

merge_keys:
- z

correlation_data: /mnt/projects/debruinz_project/july2024_census_data/filtered